### ISSUE TITLE
Run without changing ExecutionPolicy

### ISSUE THREAD

**Issue by samaguire** [MarcusWegener/Export2Dataflow#3]
Hi

I thought you'd be interested to know you can execute a script and specify the ExecutionPolicy at run time. The JSON file would need to be updated to something similar to this:

``` JSON
{
  "version": "1.1.0",
  "name": "Export to Dataflow",
  "description": "Export to Dataflow",
  "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
  "arguments": "-ExecutionPolicy Bypass -file C:\\Users\\Public\\ExternalTools\\Export2Dataflow.ps1 \"%server%\" \"%database%\" 0",
  "iconData": "data:image/png;base64,iVBORw0KGgoAAA..."
}
```

**Comment by MarcusWegener** [comment]
Hi samaguire,

thanks for the hint, but I don't want to bypass the ExecutionPolicy, it should be deliberately set by the user.
